// Generated by Xata Codegen 0.21.0. Please do not edit.
import { buildClient } from '@xata.io/client';
const tables = [{ name: 'catalog', columns: [{ name: 'title', type: 'string' }] }];
const DatabaseClient = buildClient();
const defaultOptions = {
    databaseURL: 'https://Andrew-s-workspace-c59hq8.us-east-1.xata.sh/db/it-notebook-db',
    enableBrowser: true,
    apiKey: 'xau_yn1BPmHn58t59y0gw6IwSqFMg4XzKCY9'
};
export class XataClient extends DatabaseClient {
    constructor(options) {
        super({ ...defaultOptions, ...options }, tables);
    }
}
let instance = undefined;
export const getXataClient = () => {
    if (instance)
        return instance;
    instance = new XataClient();
    return instance;
};
//# sourceMappingURL=xata.js.map